### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by akane-tendo** [wnyc/cordova-plugin-wakeuptimer#13]
********

**Comment by souly1** [comment]
@r4nm4 , any update on this issue?

**Comment by r4nm4** [comment]
@souly1 unfortunately not.
The idea of this plugin is awesome and useful, but unfortunately have so many issues.
I'm not a Java developer so I handled all issues by AngularJs.
Will see...

**Comment by souly1** [comment]
Ok, cool, I'm leaving this plugin as well, too many issues (this one, and requiring multiple alarms, which i solved by changing none js code)

**Comment by r4nm4** [comment]
in plus:
1) is not possible retrieve the alarms that you set (first rule for CRUD)
2) is not possible delete only 1 alarm
3) etc... etc..

Final score: good idea, good for starting... definitely NOT for daily application ;)

**Comment by souly1** [comment]
Sadly I had to  eventually go for another plugin: [https://github.com/katzer/cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications).

To achieve the effect of app opening once time arrives I added a option: isFullScreen and currently implemented for Android the wanted behaviour by adding in 'applyContentRecieverMethod':
if (isFullScreen){
          builder.setFullScreenIntent(contentIntent, true); <---this is the desired effect
        } else{
          builder.setContentIntent(contentIntent);
        }
