### ISSUE TITLE
Can't get it to work!

### ISSUE THREAD

**Issue by abrararies** [wnyc/cordova-plugin-wakeuptimer#3]
Hey I've been having a really hard time getting this to work. Someone please clear some things for me.
1. What is the actions param? What does it take?
2. What format does sounds take (dom element or something else)?
3. If I just provide message param (string),  will it still work?

Here is my code,

var successCallback = function(result) {
    console.log('wakeup alarm detected-- '+ result);
};

var errorCallback = function(result) {
       console.log('wakeup alarm detected-- '+ result);
};

var alarms = { type : 'snooze',
                       time : {  seconds : 60  },
                       extra : { },
                       message : "Hello!!"
                      }; 
console.log("set Alarm");
window.wakeuptimer.snooze( successCallback,  errorCallback, alarms);

Right now whenever I try to set the alarm, successCallback is called immediately where result is set to null.

Please help me out.
PS: I'm using it with Angualar

**Comment by bkammin** [comment]
successCallback be called immediately (this simply indicates that the alarm has been set), and then it should be called again after 60 seconds.

**Comment by abrararies** [comment]
Thanks @bkammin
But it still doesn't work and the "result" variable returns NULL. Is the code right?
I'm running this on IOS (8.1)

**Comment by abrararies** [comment]
Thanks @bkammin
But it still doesn't work and the "result" variable returns NULL. Is the code right?
I'm running this on IOS (8.1)

**Comment by abrararies** [comment]
@bkammin It would be really awesome if you could include a sample app in the repository.
We really need this plugin. :(

**Comment by bkammin** [comment]
I'll try to get a sample app up. Meanwhile, if you are using the snooze feature of the wakeup timer, take a look at https://github.com/wnyc/cordova-plugin-sleeptimer. It does something similar.

**Comment by abrararies** [comment]
I was testing the snooze because it didn't need date values. I actually need to use the raise the alarm on a specific time and date.
I would really appreciate a sample app. Thanks @bkammin !

**Comment by Blu-Angel** [comment]
@abrararies hi 
i just want to know did you get success in working this plugin or not? Because i am trying also but haven't  any luck yet :(

**Comment by wtetzner** [comment]
When I create an alarm, I get a result of "OK", but then the alarm never fires.

**Comment by Blu-Angel** [comment]
@wtetzner yeh same thing happening to me. It shows Alarm Set Success message but when time comes it never fires

**Comment by abrararies** [comment]
@Blu-Angel Hey
No luck yet. I am hoping tht @bkammin would add a sample app and make my life easier. ;)

**Comment by bkammin** [comment]
I've been swamped on other project lately and haven't had time to put
together a sample app -- if you could send a sample app with your code,
I'll get it working and add it to the repo.

**Comment by Blu-Angel** [comment]
@bkammin Thank that would be very nice. I will upload test app in a day or two.

**Comment by Blu-Angel** [comment]
@bkammin  following is the link for test app
https://www.dropbox.com/s/9fxh5de8pod0hch/testAlarm.rar?dl=0

I test in Mobiles and also in Genemotion Emulators but not succeed

**Comment by bkammin** [comment]
I created a working example in the github repository using your code -
thanks for contributing. Let me know if it works for you.

**Comment by wtetzner** [comment]
I used the working example to get my program working. If the app is open at the time the alarm should trigger, it calls my success function. However, if my app is closed, then when the alarm time comes, it opens my app, but it doesn't call the success function.

Is there something I need to do to get that working?

**Comment by bkammin** [comment]
In my testing the success function was called in the sample app with the
app in the background when the alarm expired (I'm testing on a Samsung S3
running 4.4.2).

You could make sure the KeepRunning flag is config.xml is not set to false
(it defaults to true). If it is set to false, the execution of cordova
webview code is halted when the app is in the background.

<preference name="KeepRunning" value="true" />

**Comment by Blu-Angel** [comment]
@bkammin Thanks for update. and apologise for my late reply. I am testing that maybe i will have some other new questions about this plugin and i would like to start new issue with sample app soon. Thanks.

**Comment by rafaelkendy** [comment]
Hi, where can i find cordova.js that is missing?

**Comment by bkammin** [comment]
cordova.js is not included in the plugin - it is installed when you create a Cordova app (see http://cordova.apache.org)

**Comment by sabirali007** [comment]
can i take sample app?
