### ISSUE TITLE
any tutorials?

### ISSUE THREAD

**Issue by joonthepark** [wnyc/cordova-plugin-wakeuptimer#6]
in my index.html file, i put 	 
<script type="text/javascript">
	window.wakeuptimer.wakeup( successCallback,  errorCallback, 
		  // a list of alarms to set
		   {
          alarms : [{
            type : 'onetime',
            time : { hour : 14, minute : 02 },
            extra : { message : 'json containing app-specific information to be posted when alarm triggers' }, 
            message : 'Alarm has expired!'
       }] 
   }
);
</script>

but not working. can you provide some thorough tutorials?

**Comment by bkammin** [comment]
See https://github.com/wnyc/cordova-plugin-wakeuptimer/tree/master/examples/SimpleAlarmExample

**Comment by sgatade** [comment]
Sorry but the example in the github doesnt seem to be doing anything with the wakeup timer!
